name: 'Deploy Hugo Site'
description: 'Deploy a Hugo based site to a .github.io repository'

branding:
  icon: 'cloud-drizzle'
  color: 'gray-dark'

inputs:
  destination_repo:
    description: 'The repository the build output will be committed to'
    required: true

  destination_token:
    description: 'A GitHub API token with read and commit access to the destination repo'
    required: true

  hugo_args:
    description: 'The arguments to pass to Hugo when buliding the site'
    required: true
    default: ''

  build_dir:
    description: 'The directory into which Hugo writes the built site'
    required: true
    default: 'public'

runs:
  using: 'docker'
  image: 'Dockerfile'
